package de.uni_passau.fim.heck.githubinterface.datadefinitions;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import de.uni_passau.fim.seibt.gitwrapper.repo.Commit;

import java.util.Date;

/**
 * A skeleton for information about Events.
 */
public abstract class EventData {

    /**
     * The User that created the Event.
     */
    @SerializedName(value = "user", alternate = {"actor"})
    public UserData user;

    /**
     * The date and time the Event was created.
     */
    public Date created_at;

    /**
     * The event typ.
     */
    public String event;

    /**
     * A generic event.
     */
    public class DefaultEventData extends EventData {}

    /**
     * An Event generated by a change of labels.
     */
    public class LabeledEventData extends EventData {

        /**
         * Information about the label
         */
        public LabelData label;

        /**
         * Information about the label
         */
        public class LabelData {

            /**
             * The name of the label.
             */
            public String name;
        }
    }

    /**
     * An Event generated by referencing an {@link IssueData#number Issue} in a {@link Commit}.
     */
    public class ReferencedEventData extends EventData {

        /**
         * The commit references.
         */
        @Expose(deserialize = false)
        public Commit commit;
    }
}
