package de.uni_passau.fim.heck.githubinterface.datadefinitions;

import java.util.Date;

import com.google.gson.annotations.SerializedName;

public abstract class EventData {

    @SerializedName(value = "user", alternate = {"actor"})
    public UserData user;
    public Date created_at;
    public String event;

    /**
     * A generic event.
     */
    public class DefaultEventData extends EventData { }

    /**
     * An event generated by a change of labels.
     */
    public class LabeledEventData extends EventData {
        public LabelData label;

        public class LabelData {
            public String name;
        }
    }

    /**
     * An event generated by referencing an issue in an commit.
     */
    public class ReferencedEventData extends EventData {
        public String commit_id;
    }
}
