package de.uni_passau.fim.gitwrapper;

import java.time.OffsetDateTime;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * A skeleton for information about Events.
 */
public abstract class EventData {

    @SerializedName(value = "user", alternate = {"actor"})
    UserData user;
    OffsetDateTime created_at;
    String event;

    /**
     * The User that created the Event.
     */
    public UserData getUser() {
        return user;
    }

    /**
     * The date and time the Event was created.
     */
    public OffsetDateTime getCreateDate() {
        return created_at;
    }

    /**
     * The event typ.
     */
    public String getEvent() {
        return event;
    }

    /**
     * A generic event.
     */
    class DefaultEventData extends EventData {}

    /**
     * An Event generated by a change of labels.
     */
    public class LabeledEventData extends EventData {

        LabelData label;

        /**
         * The name of the label.
         */
        public String getName() {
            return label.name;
        }

        /**
         * Information about the label
         */
        class LabelData {
            String name;
        }
    }

    /**
     * An Event generated by referencing an {@link IssueData#number Issue} in a {@link Commit}.
     */
    public class ReferencedEventData extends EventData {

        @Expose(deserialize = false)
        Commit commit;

        /**
         * The commit references.
         */
        public Commit getCommit() {
            return commit;
        }
    }
}
